apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenticaitraining-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agenticaitraining-main
  template:
    metadata:
      labels:
        app: agenticaitraining-main
    spec:
      containers:
      - name: agenticaitraining-main
        image: akhilspalli/agenticaitraining-main:latest
        ports:
        - containerPort: 8080
